### ISSUE TITLE
More of a future update

### ISSUE THREAD

**Issue by brynnie1** [oosayeroo/qb-moonshine#1]
Ability to turn on blips on map for locations like the picking the barley, and ingredients ect

**Comment by oosayeroo** [comment]
That's a good idea. I'll look into that :) Sent from my Galaxy
-------- Original message --------From: brynnie1 ***@***.***> Date: 20/07/2022  14:03  (GMT+00:00) To: oosayeroo/qb-moonshine ***@***.***> Cc: Subscribed ***@***.***> Subject: [oosayeroo/qb-moonshine] More of a future update (Issue #1) 
Ability to turn on blips on map for locations like the picking the barley, and ingredients ect
