### ISSUE TITLE
picking up

### ISSUE THREAD

**Issue by EdwinShima** [oosayeroo/qb-moonshine#4]
Press E to pick up 
when i do that the he digs it out the ground but the item dose not show in my inventory

**Comment by oosayeroo** [comment]
Hi. Do you have the updated version as of 3 days ago?

**Comment by EdwinShima** [comment]
Yes i downloaded it last night

**Comment by oosayeroo** [comment]
I've tested it out and it's working for me. Have you made sure you've got the items in shared/items.lua correct. Specifically the m-potato

**Comment by EdwinShima** [comment]
![image](https://user-images.githubusercontent.com/85160596/183071276-bbe8ccb9-b9d8-4223-9e87-cbb62f1f3d33.png)
yes 

dose not matter where is the sheard.lua the i put it right just to be sure

**Comment by oosayeroo** [comment]
I'm not sure what the issue could be. If you join my discord through the link I can try help you fix the issue later on as I'm not at home right nowSent from my Galaxy
